# Site settings
title: Dustin Laverick
email: 
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://laverick.org" # the base hostname & protocol for your site
twitter_username: laverick
github_username:
permalink: :title

# Build settings
markdown: kramdown


contact: "https://laverick.paperform.co"
